name: Setup
description: Setup
runs:
  using: composite
  steps:
    - name: Setup Node.js 🔠
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version-file: package.json

    - name: Install Dependencies 🪛
      shell: bash
      run: corepack enable && pnpm install
