name: Setup
description: Setup
runs:
  using: composite
  steps:
    - name: Setup Node.js 🔠
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version-file: package.json

    - name: Install Dependencies 🪛
      shell: bash
      run: corepack enable && pnpm install
