name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: 👷 Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup
      - name: Building
        run: pnpm build

  eslint:
    name: 🪥 ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup
      - run: pnpm run format-check
      - run: pnpm run lint

  gitleaks:
    name: 🔒 Run Git leaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup
      - name: Gitleaks
        run: pnpm run leaks
        shell: bash

  unit-test:
    name: 👔 Run Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [18, 20, 22]
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ matrix.version }}
      - name: Install dependencies and build
        run: corepack enable && pnpm install --no-frozen-lockfile --ignore-scripts && npm run build
      - name: Testing
        run: pnpm test
