name: 📢 publish

on:
  push:
    tags:
      - "release/**"

env:
  NODE_VERSION: 20.x

jobs:
  publish:
    name: 📢 Publish
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/
      # Skip post-install scripts here, as a malicious
      # script could steal NODE_AUTH_TOKEN.
      - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          version: 10.7.1
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --ignore-scripts
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.CI_NPM_READ_ORG }}
      # `npm rebuild` will run all those post-install scripts for us.
      - run: npm rebuild && npm run prepare --if-present

      - name: Publish to NPM Package Registry
        run: npm publish --access=public
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.CI_NPM_REGISTRY }}
          # NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
